### ISSUE TITLE
Handle effective* in include/exclude

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/ec-cli#1052]
With https://github.com/enterprise-contract/enterprise-contract-controller/issues/191, the include/exclude list may contain objects instead of just strings. See that issue for more details.

This is about teaching the CLI to handle those correctly.

Consider the following example:
```yaml
sources:
  - config:
      exclude:
        - step_image_registries
        - name: tasks
          effectiveUntil: "2024-01-01T00:00:00Z"
        - name: tests
          effectiveOn: "2023-10-01T00:00:00Z"
      include:
        - '@redhat'
    data:
      ...
    policy:
      ...
```

`step_image_registries` is always excluded. `tasks` is only excluded until January 1st, 2024. `tests` is excluded starting on January 1st, 2023.

Eventually, we may want to emit a warning in certain cases. For example, if a certain violation that is being excluded today will be included in a few days (either via exclude entry with effectiveUntil, or include entry with effectiveOn). Let's keep that out of scope for this issue.
