### ISSUE TITLE
Change the data model for Acceptable Bundles

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/ec-cli#1291]
The [acceptable bundles](https://enterprisecontract.dev/docs/ec-policies/acceptable_bundles.html) data is modeled as such:

```yaml
<type>-bundles:
  <repo>:
    - digest: <digest>
      effective_on: <timestamp>
      tag: <tag
```
For example:

```yaml
task-bundles:
  quay.io/redhat-appstudio-tekton-catalog/task-buildah:
    - digest: sha256:c37e542031de193398cd54463af146e42539b5f5c9082df56d65354494566db0
      effective_on: "2023-11-06T00:00:00Z"
      tag: "0.1"
    - digest: sha256:97f21661e237735af04b37feeeaedd328424bfa0ebd4cd0f79ac39cde17137f6
      effective_on: "2023-10-25T00:00:00Z"
      tag: "0.2"
```

Then there's rego that interprets this data to do the right thing.

Sometimes we use the value of `tag` to determine what is the latest version for that particular tag. In such cases, there are really virtual lists, one for each `tag` value.

The reality is that there is always a `tag` value, and we could make that a requirement. This issue is about changing how the data is represented, for example:

```yaml
task-bundles:
  quay.io/redhat-appstudio-tekton-catalog/task-buildah:
    "0.1":
      - digest: sha256:c37e542031de193398cd54463af146e42539b5f5c9082df56d65354494566db0
        effective_on: "2023-11-06T00:00:00Z"
    "0.2":
      - digest: sha256:97f21661e237735af04b37feeeaedd328424bfa0ebd4cd0f79ac39cde17137f6
        effective_on: "2023-10-25T00:00:00Z"
```

This would impact `ec track bundle` (may need to add code to convert things on the fly to allow for an easier transition), and ec-policies (may need to support both formats for a bit).

**Comment by simonbaird** [comment]
Another possible way to do it:

```yaml
task-bundles:
  quay.io/redhat-appstudio-tekton-catalog/task-buildah:0.1:
    - digest: sha256:c37e542031de193398cd54463af146e42539b5f5c9082df56d65354494566db0
      effective_on: "2023-11-06T00:00:00Z"
  quay.io/redhat-appstudio-tekton-catalog/task-buildah:0.2:  
    - digest: sha256:97f21661e237735af04b37feeeaedd328424bfa0ebd4cd0f79ac39cde17137f6
      effective_on: "2023-10-25T00:00:00Z"
```
