### ISSUE TITLE
Include `expires_on` in the acceptable bundles list

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/ec-cli#1332]
The acceptable bundles list looks like this today:

```yaml
task-bundles:
  quay.io/redhat-appstudio-tekton-catalog/task-buildah:
    - digest: sha256:163009699fca1c5c043516d84986b44f8b6ef25418c97eed51d12518a94d552e
      effective_on: "2024-03-09T00:00:00Z"
      tag: "0.1"
    - digest: sha256:5db20956b51725f1b50f02d21413cd7d0c082e4f51364c54e51f78dfa75893a4
      effective_on: "2024-03-09T00:00:00Z"
      tag: "0.1"
    - digest: sha256:1ee1d570b3cf7feaf85a22c828076e798a57266ffcfea41c1aa0e9f85b0a885a
      effective_on: "2024-03-07T00:00:00Z"
      tag: "0.1"
    - digest: sha256:351af2c0e5eeb92a5d6d4083847c1559475b596cda7671f489756d5302a4c847
      effective_on: "2024-02-16T00:00:00Z"
      tag: "0.1"
    - digest: sha256:155ba11fda63c10ac3a824f4c2db385c22299551124db5d239b325b576249839
      effective_on: "2024-02-10T00:00:00Z"
      tag: "0.1"
    - digest: sha256:38f557374d73ce220237c507b60ce653430284c5b81a29ce840fcb48081855d6
      effective_on: "2024-02-04T00:00:00Z"
      tag: "0.1"
```

As you can see each item has an `effective_on` value. The data is sorted in descending order by the `effective_on` date. (Newer records are at the top.)

At a certain `effective_on` date/time, that particular digest is the oldest acceptable value. Anything newer is also ok to use. Anything older is treated as if it is not even in the list; those are expired items. 

In other words, an item becomes expired when the `effective_on` date of a newer item is reached. The `effective_on` value of record N is the `expires_on` value of record `N+1`.

The most recent item does not have an expiration date because there is no newer item to be used. (This is true today, but may change in the future when we add support for deprecating a bundle repo altogether.)

This story is about enhancing `ec track bundle` to also include an `expires_on` date in the acceptable bundles items.

NOTE: See this [commit](https://github.com/enterprise-contract/ec-cli/commit/4a09043197194ebc3a6297d1548a3ca203e5a35e) for inpiration.

**Acceptance Criteria**

* Each item in the list of acceptable bundles includes an `expires_on` date. It also continue to include an `effective_on` value to make the transition easier.
