### ISSUE TITLE
[BUG] "validate input" does not handle multiple source groups

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/ec-cli#1688]
## Describe the Bug

When using a policy config that relies on more than one source group, the `ec validate input` command only takes into account the _last_ policy source group. Violations and warnings from Previous policy source groups are completely ignored.

## Steps to Reproduce

Assuming the current working directory is `/tmp/peaceful-roentgen`,  create a couple of dummy policy rules in different directories, e.g.

```
$ cat policies1/spam.rego 
package policies1.spam

import rego.v1

# METADATA
# title: Spam
# description: Spam spam spam
# custom:
#   short_name: valid
#
deny contains result if {
	value := object.get(input, "spam", false)
	not value
	result := {
		"msg": "spam is not true",
		"code": "spam.valid",
	}
}

$ cat policies2/ham.rego 
package policies1.ham

import rego.v1

# METADATA
# title: Ham
# description: Ham ham ham
# custom:
#   short_name: delicious
#
deny contains result if {
	value := object.get(input, "ham", "yucky")
	value != "delicious"
	result := {
		"msg": "ham is not delicious",
		"code": "ham.delicious",
	}
}
```

Create a policy config pointing to the policy rules above:

```yaml
---
sources:
  - policy:
    - /tmp/peaceful-roentgen/policies1
  - policy:
    - /tmp/peaceful-roentgen/policies2

```

Create a dummy input file:

```json
{
  "spam": false,
  "ham": "rotten"
}
```

Now use EC CLI to verify the input file:

```
🐚 ec validate input --policy policy.yaml --file input.json --output yaml | yq .
ec-version: v0.5.1
effective-time: "2024-06-10T19:37:21.211638463Z"
filepaths:
  - filepath: input.json
    success: false
    success-count: 1
    successes: null
    violations:
      - metadata:
          code: ham.delicious
        msg: ham is not delicious
    warnings: []
policy:
  sources:
    - policy:
        - /tmp/peaceful-roentgen/policies1
    - policy:
        - /tmp/peaceful-roentgen/policies2
success: false
```

Notice how the expected `spam.valid` violation is not listed.

Reverse the order of the policy sources:
```
---
sources:
  - policy:
    - /tmp/peaceful-roentgen/policies2
  - policy:
    - /tmp/peaceful-roentgen/policies1
```

Run the same command again:

```
🐚 ec validate input --policy policy.yaml --file input.json --output yaml | yq .
ec-version: v0.5.1
effective-time: "2024-06-10T19:38:35.957283421Z"
filepaths:
  - filepath: input.json
    success: false
    success-count: 1
    successes: null
    violations:
      - metadata:
          code: spam.valid
        msg: spam is not true
    warnings: []
policy:
  sources:
    - policy:
        - /tmp/peaceful-roentgen/policies2
    - policy:
        - /tmp/peaceful-roentgen/policies1
success: false
```

Notice how the `spam.valid` violation is there (good), but the `ham.delicious` violation is now gone (bad).

## Expected Behavior

Every policy source group should be evaluated. Violations and warnings should be combined in the final report.

## Actual Behavior

Only the last source group is taken into account.

## Environment Details

- **Operating System:**
- **`ec` CLI Version, run `ec version --short`:** v0.5.1
- **Shell:** Linux fedora 6.8.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sun May 26 20:05:41 UTC 2024 x86_64 GNU/Linux
- **Additional context:**

I was not able to reproduce this behavior with the `ec validate image` command. This seems to be isolated to `ec validate input`.

It is unclear if this is just a reporting issue. When using the `--debug` flag, I only see the source URL of one of the source groups. This may be an incorrect construction of ConftestEvaluator.

**Comment by mbestavros** [comment]
@lcarva I was able to replicate the bug using your test setup (thanks!)

I changed the data in `input.json` as such:

```json
{
    "spam": false,
    "ham": "delicious"
}
```

This _should_ still result in a single violation, from `spam.rego`. But running it against this `policy.yaml`:

```yaml
---
sources:
  - policy:
    - /tmp/peaceful-roentgen/policies1
  - policy:
    - /tmp/peaceful-roentgen/policies2
```

resulted in no violations at all. So that suggests it's more than a simple output bug.
