### ISSUE TITLE
[BUG] context deadline exceeded

### ISSUE THREAD

**Issue by ralphbean** [enterprise-contract/ec-cli#1730]
## Describe the Bug

When trying to validate an artifact at release time, ec-cli failed with violations that indicate that it timed out trying to talk to quay. This happened 3 or 4 times to me in the last week.

I suspect quay configuration changes may be causing the increase in frequency, but I cannot prove it.

## Steps to Reproduce

I cannot reproduce. :(

## Expected Behavior

Successful ec validation.

## Actual Behavior

ec reports:

```yaml
violations:
- metadata:
    code: builtin.attestation.signature_check
    description: The attestation signature matches available signing materials.
    title: Attestation signature check passed
  msg: 'Image attestation check failed: Get "https://quay.io/v2/": context deadline exceeded'
- metadata:
    code: builtin.image.signature_check
    description: The image signature matches available signing materials.
    title: Image signature check passed
  msg: 'Image signature check failed: Get "https://quay.io/v2/": context deadline exceeded'
```

## Screenshots or Terminal Output

N/A.

## Environment Details

This happened in the konflux release-serivce pipelines.

## Possible Solution

If quay is down, you can't help it. But, you can retry! Can you evaluate your retry mechanism to improve resilience of the end to end process?
